### ISSUE TITLE
No feedback when attempting to delete a dependency plugin

### ISSUE THREAD

**Issue by bryanhiggins** [blackberry/webworks-gui#113]
We should either not show the trash can icon or display an error message.

**Comment by rcruz** [comment]
WebWorks CLI returns no error message or error code when deleting a dependency plugin. The correct place to fix this is within the CLI.

**Comment by bryanhiggins** [comment]
From latest cordova-cli:

 ~/Cordova/cordova-cli/bin/cordova plugin rm org.apache.cordova.file
/Users/jsoref/Cordova/cordova-cli/node_modules/q/q.js:126
throw e;
^
Error: The plugin 'org.apache.cordova.file' is required by (org.apache.cordova.file-transfer), skipping uninstallation.
at runUninstallPlatform (/Users/jsoref/Cordova/cordova-plugman/src/uninstall.js:183:30)
at Function.module.exports.uninstallPlatform (/Users/jsoref/Cordova/cordova-plugman/src/uninstall.js:55:12)
at /Users/jsoref/Cordova/cordova-cli/src/plugin.js:173:58
at _fulfilled (/Users/jsoref/Cordova/cordova-cli/node_modules/q/q.js:798:54)
at self.promiseDispatch.done (/Users/jsoref/Cordova/cordova-cli/node_modules/q/q.js:827:30)
at Promise.promise.promiseDispatch (/Users/jsoref/Cordova/cordova-cli/node_modules/q/q.js:760:13)
at /Users/jsoref/Cordova/cordova-cli/node_modules/q/q.js:821:14
at flush (/Users/jsoref/Cordova/cordova-cli/node_modules/q/q.js:108:17)
at process._tickCallback (node.js:415:13)
at Function.Module.runMain (module.js:499:11)
joshs-mbp:dep-hell-2 jsoref$ echo $?
8

**Comment by rcruz** [comment]
Since an error is now reported to stderr when deleting dependency plugins, a proper error message is displayed in the GUI. No additional changes required.
![screen shot 2014-04-19 at 11 00 01 pm](https://cloud.githubusercontent.com/assets/384080/2749924/1704f360-c838-11e3-954c-cb6e60206731.png)

Taken from build 2.1.0.5
