### ISSUE TITLE
Error Installing certificates on Windows 7 (home edition) using the %HOMEPATH% variable

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#33]
When specifying the location of your certificate, you get this error in node:

Error: ENOENT, no such file or directory 'C:\Program Files (x86)\BlackBerry\BB10
 WebWorks SDK 2.0.0.54\webworks-ui\bin\%HOMEPATH%\Local Settings\Application Dat
a\Research In Motion\bbidtoken.csk'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at Object.module.exports.copyFile (C:\PROGRA~2\BLACKB~1\BB10WE~1.54\WEBWOR~2
\lib\util.js:64:16)
    at addSigningKey (C:\PROGRA~2\BLACKB~1\BB10WE~1.54\WEBWOR~2\routes\certifica
te.js:58:17)
    at module.exports.get (C:\PROGRA~2\BLACKB~1\BB10WE~1.54\WEBWOR~2\routes\cert
ificate.js:114:17)
    at callbacks (C:\PROGRA~2\BLACKB~1\BB10WE~1.54\WEBWOR~2\node_modules\express
\lib\router\index.js:164:37)
    at param (C:\PROGRA~2\BLACKB~1\BB10WE~1.54\WEBWOR~2\node_modules\express\lib
\router\index.js:138:11)
    at pass (C:\PROGRA~2\BLACKB~1\BB10WE~1.54\WEBWOR~2\node_modules\express\lib\
router\index.js:145:5)
    at Router._dispatch (C:\PROGRA~2\BLACKB~1\BB10WE~1.54\WEBWOR~2\node_modules\
express\lib\router\index.js:173:5)
    at Object.router (C:\PROGRA~2\BLACKB~1\BB10WE~1.54\WEBWOR~2\node_modules\exp
ress\lib\router\index.js:33:10)
127.0.0.1 - - [Sat, 18 Jan 2014 02:59:48 GMT] "GET /certificate?cmd=add&path=C%3
A%5CUsers%5Cjgee%5CAppData%5CLocal%5CResearch+In+Motion%5Cbbidtoken.csk HTTP/1.1
" 500 1118 "http://localhost:3123/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWe
bKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.76 Safari/537.36"

(Tested only on WIn 7-64b Home edition so far)

**Comment by bryanhiggins** [comment]
Is this still valid?

**Comment by jengee** [comment]
Error is still occuring even on Win7-64b Enterprise edition.

I provided the full path of where my key is and I get an error: 
![patherror](https://f.cloud.github.com/assets/549345/2172572/58d10db8-9595-11e3-9143-f280ee76195b.PNG)
